### ISSUE TITLE
Sounds abspielen

### ISSUE THREAD

**Issue by Shishaclub** [GreedTECH/GreedTECHIssues#3]
**Is your feature request related to a problem? Please describe.**
No it its not. Its just a Idea.

**Describe the solution you'd like**
I´d like to request sounds like the YouTube Videos. I would prefer a system thats the same as the Video request, just without the Video.

**Describe alternatives you've considered**
I see no other solution thats also easy like that,.

**Additional context**
In the last few weeks some situations needed a sound request System. An example: Zander looks for the Star Wars melody an didnt know it. He requestet the Intro but i had no other option than to play the video also. Thats a little unsatisfying.

**Comment by DaWenning** [comment]
Resolved
